import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "../styles/Home.module.css";
import { Main } from "@/src/components/main";
import YourComponent, {Headline} from "@/src/components/Headline/Headline";
import Alert from "@/src/components/Headline/Headline";
import { Header } from "@/src/components/Header";
import { useCallback } from "react";


const inter = Inter({ subsets: ["latin"] });

export default function Home() {

  const handleClick = useCallback((e) => {
    /* e.preventDefault(); */
   alert(123);
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

      <a href="/about" 
         onClick={handleClick}>
        ボタン
      </a>

      <Headline  page="index"
      >
        {<div className={styles.center}>foo</div>}
      </Headline>
      <Alert Click={()=> alert("Clicked!")} page="index" />
      <Main />
    </>
  );
}
